---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[harstorage::mongo]
      - recipe[harstorage::install]
    attributes:
      harstorage:
        browsermob:
          source: 'https://s3.amazonaws.com/uploads.hipchat.com/32081/488539/K4v89viOcJrKfTM/browsermob_proxy.deb'
  - name: browsermob
    run_list:
      - recipe[harstorage::default]
      - recipe[harstorage::browsermob]
    attributes:
      harstorage:
        browsermob:
          source: 'https://s3.amazonaws.com/uploads.hipchat.com/32081/488539/K4v89viOcJrKfTM/browsermob_proxy.deb'
    excludes:
      - ubuntu-14.04
